Refactor and add new features
eloiza-souza/challenge-bug-hunting pull request #1
Opened 2024-12-27 16:52 UTC by eloiza-souza

### Purpose
Implement the changes suggested in the **Bug Hunting** challenge, ensuring code improvements and adding the proposed new features.

---

### Changes Made

#### 1. **Code Refactoring**
- The code was completely refactored following the principles of **Best Programming Practices** and **Object-Oriented Programming (OOP)**.
- The following were created:
  - **New Classes**: To better organize responsibilities and facilitate code maintenance.
  - **Enumerations**: To represent fixed values more clearly and safely.
  - **Specific Methods**: To encapsulate behaviors and avoid code duplication.

#### 2. **Improvements and New Features**
- All the functionalities suggested in the challenge were implemented.

---

### Impacts
- **Positive Impact**:
  - More organized, readable, and maintainable code.
  - New features added as per the challenge requirements.
- **Negative Impact**:
  - No negative impact expected, but extensive testing is recommended to ensure stability.

---

2024-12-27 17:22 UTC, andersongadelha reviewed
Muito massa sua entrega Eloiza esses commits em ingles seguindo o padrão 🤌

2024-12-27 17:22 UTC, andersongadelha commented on src/controller/VideoController.java
> +    private void searchByTitle(Scanner scanner) {
Uma sugestão aqui seria deixar esses métodos de operações de vídeo na VideoService

2024-12-27 17:22 UTC, andersongadelha commented on src/util/FileHandler.java
> +import java.io.*;
Tenho o habito de evitar usar essa importação geral do pacote com *.
Gosto sempre de deixar explicito exatamente quais imports cada classe esta utilizando.

2024-12-27 17:29 UTC, eloiza-souza commented on src/util/FileHandler.java
> +import java.io.*;
Também costumo fazer isso, mas como são muitos imports da mesma classe a própria IDE está fazendo isso e não estou conseguindo especificar cada um. Sabe como faço para que isso não aconteça?

2024-12-27 17:51 UTC, andersongadelha commented on src/util/FileHandler.java
> +import java.io.*;
Nas configurações do intelliJ podemos alterar isso.
Settings > Editor > Code Style > Java ( aqui tem uma aba chamada imports que podemos escolher a quantidade de imports necessários para agrupar. Eu coloquei um valor 999

2024-12-27 18:00 UTC, eloiza-souza commented on src/util/FileHandler.java
> +import java.io.*;
Obrigada! Vou mudar lá e alterar o código

2024-12-27 18:15 UTC, eloiza-souza commented on src/controller/VideoController.java
> +    private void searchByTitle(Scanner scanner) {
Sugestão implementada!

2024-12-30 16:53 UTC, andersongadelha commented on src/controller/VideoController.java
> +    private void searchByTitle(Scanner scanner) {
Massa, por mim aprovado!

2025-01-02 13:37 UTC, joaocandidozup commented
Muito legal a aplicação, como sugestão poderia implementar uma validação para ser obrigatório adicionar os 4 dígitos no ano da data de publicação para nao salvar nesse formato:
![Captura de tela 2025-01-02 103610](https://github.com/user-attachments/assets/a9e89c34-5d8a-4e9c-9d48-6f88f858334d)

2025-01-02 17:44 UTC, eloiza-souza commented
Implementação de validação do ano na data realizada. Obrigada @joaocandidozup

2025-01-02 17:59 UTC, eloiza-souza commented
> Muito legal a aplicação, como sugestão poderia implementar uma validação para ser obrigatório adicionar os 4 dígitos no ano da data de publicação para nao salvar nesse formato: ![Captura de tela 2025-01-02 103610](https://private-user-images.githubusercontent.com/190003946/399713492-a9e89c34-5d8a-4e9c-9d48-6f88f858334d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NDEwMjcsIm5iZiI6MTczNTg0MDcyNywicGF0aCI6Ii8xOTAwMDM5NDYvMzk5NzEzNDkyLWE5ZTg5YzM0LTVkOGEtNGU5Yy05ZDQ4LTZmODhmODU4MzM0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNzU4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzFmYThiZDZkYzg2N2ZkN2JhNDBjMjdhODhjYjY0NzE4MTg5ODE4MTI1NjJmZWZhNmI1YzEzMWQ3NWU4M2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VMxTdzpiho8_knvYXcMq0EV1szREVA8e0fgNSy_hGBE)

Implementação de validação do ano na data realizada. Obrigada!

2025-01-02 18:43 UTC, monicaribeirozup requested changes

2025-01-02 18:43 UTC, monicaribeirozup commented on src/service/VideoManager.java
> +public abstract class VideoManager {
```suggestion
public abstract class VideoManagerService {
```

2025-01-02 18:43 UTC, monicaribeirozup commented on src/service/VideoValidator.java
> +public abstract class VideoValidator {
Sugestão: colocar essa classe na pasta útil, pois ela não está parecendo muito ser um service e poderia ser reutilizada por outros services.

2025-01-02 18:44 UTC, monicaribeirozup commented on src/service/VideoManager.java
> +public abstract class VideoManager {
Sugestão: manter a padronização e colocar o sufixo "Service" nesta classe.

2025-01-02 18:52 UTC, eloiza-souza commented on src/service/VideoManager.java
> +public abstract class VideoManager {
Implementado! Obrigada

2025-01-02 18:56 UTC, eloiza-souza commented on src/service/VideoValidator.java
> +public abstract class VideoValidator {
Feito! Obrigada

2025-01-03 17:15 UTC, merged